import type { Metadata } from "next";
import ProtectedLayout from "./PotectedLayout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProtectedRootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ProtectedLayout>
            {children}
        </ProtectedLayout>
    );
}
